#!/bin/bash
#
# test connection map lookups (Need root permission)
#

count="0"
DELAY="15"
NTHREADS="2"
NRENTRIES="100"

while true; do
        count=$[$count + 1]
        echo "****Running interation**** $count"
	insmod net_table.ko max_entries=$NRENTRIES max_threads=$NTHREADS
        sleep $DELAY
	rmmod net_table
	dmesg -c
done


